# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cmdata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
