# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkcm', '0002_auto_20170204_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimemapinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuetime', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('crime', models.CharField(blank=True, max_length=50, null=True)),
                ('crimecat', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=500, null=True)),
            ],
            options={
                'db_table': 'crimemapinfo',
                'managed': False,
            },
        ),
    ]
