# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkcm', '0003_crimemapinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdata',
            name='URL',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cmdata',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
