# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkcm', '0004_auto_20170204_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdata',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
