# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkcm', '0007_delete_hongkongdistricts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HongKongDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, unique=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('Districts', models.CharField(max_length=200)),
            ],
        ),
    ]
